name: Build
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2

      - uses: hmarr/debug-action@v2

      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@pouch-ph'

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test
